services:
  # Backend API Service
  - type: web
    name: estate-house-plans-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: ""
      - key: DB_NAME
        value: estate_house_plans
      - key: DB_PORT
        value: 3306

  # Frontend Service
  - type: static_site
    name: estate-house-plans-frontend
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://estate-house-plans-backend.onrender.com/api 